// generated by design/nami-art/pack_clips.py from the Wan clips; do not edit by hand
import type { Clip } from './art';

export const WAN_CLIPS: Record<string, Clip> = {
  "calling@loop": {
    "src": "/nami/clips/calling-loop.mp4",
    "frames": 48,
    "cols": 1,
    "fps": 16
  },
  "celebrate@loop": {
    "src": "/nami/clips/celebrate-loop.mp4",
    "frames": 48,
    "cols": 1,
    "fps": 16
  },
  "help@loop": {
    "src": "/nami/clips/help-loop.mp4",
    "frames": 48,
    "cols": 1,
    "fps": 16
  },
  "idle@loop": {
    "src": "/nami/clips/idle-loop.mp4",
    "frames": 48,
    "cols": 1,
    "fps": 16
  },
  "idle~acknowledged": {
    "src": "/nami/clips/idle-to-acknowledged.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-acknowledged.rev.mp4"
  },
  "idle~calling": {
    "src": "/nami/clips/idle-to-calling.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-calling.rev.mp4"
  },
  "idle~celebrate": {
    "src": "/nami/clips/idle-to-celebrate.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-celebrate.rev.mp4"
  },
  "idle~greeting": {
    "src": "/nami/clips/idle-to-greeting.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-greeting.rev.mp4"
  },
  "idle~heart": {
    "src": "/nami/clips/idle-to-heart.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-heart.rev.mp4"
  },
  "idle~help": {
    "src": "/nami/clips/idle-to-help.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-help.rev.mp4"
  },
  "idle~listening": {
    "src": "/nami/clips/idle-to-listening.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-listening.rev.mp4"
  },
  "idle~point-left": {
    "src": "/nami/clips/idle-to-point-left.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-point-left.rev.mp4"
  },
  "idle~point-right": {
    "src": "/nami/clips/idle-to-point-right.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-point-right.rev.mp4"
  },
  "idle~quiet": {
    "src": "/nami/clips/idle-to-quiet.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-quiet.rev.mp4"
  },
  "idle~reminder": {
    "src": "/nami/clips/idle-to-reminder.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-reminder.rev.mp4"
  },
  "idle~speaking": {
    "src": "/nami/clips/idle-to-speaking.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-speaking.rev.mp4"
  },
  "idle~stand": {
    "src": "/nami/clips/idle-to-stand.mp4",
    "frames": 21,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-stand.rev.mp4"
  },
  "idle~thinking": {
    "src": "/nami/clips/idle-to-thinking.mp4",
    "frames": 17,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/idle-to-thinking.rev.mp4"
  },
  "listening@loop": {
    "src": "/nami/clips/listening-loop.mp4",
    "frames": 48,
    "cols": 1,
    "fps": 16
  },
  "quiet@loop": {
    "src": "/nami/clips/quiet-loop.mp4",
    "frames": 48,
    "cols": 1,
    "fps": 16
  },
  "reminder@loop": {
    "src": "/nami/clips/reminder-loop.mp4",
    "frames": 48,
    "cols": 1,
    "fps": 16
  },
  "stand~walk": {
    "src": "/nami/clips/stand-to-walk.mp4",
    "frames": 13,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/stand-to-walk.rev.mp4"
  },
  "stand~walk-left": {
    "src": "/nami/clips/stand-to-walk-left.mp4",
    "frames": 13,
    "cols": 1,
    "fps": 30,
    "rev": "/nami/clips/stand-to-walk-left.rev.mp4"
  },
  "swim@loop": {
    "src": "/nami/clips/swim-loop.mp4",
    "frames": 48,
    "cols": 1,
    "fps": 16
  },
  "thinking@loop": {
    "src": "/nami/clips/thinking-loop.mp4",
    "frames": 48,
    "cols": 1,
    "fps": 16
  },
  "greeting@loop": {
    "src": "/nami/clips/greeting-loop.mp4",
    "frames": 16,
    "cols": 1,
    "fps": 16
  }
};
